# Generated by Django 6.0.7 on 2026-07-25 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('7', '7 gün'), ('15', '15 gün'), ('30', '30 gün')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='AZN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Gözləmədə'), ('paid', 'Ödənilib (DEMO)'), ('failed', 'Uğursuz')], default='pending', max_length=10)),
                ('mock_reference_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promosyon (Demo Ödəniş)',
                'verbose_name_plural': 'Promosyonlar (Demo Ödənişlər)',
                'ordering': ['-created_at'],
            },
        ),
    ]
