# Generated by Django 6.0.7 on 2026-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-is_featured', '-is_vip', '-is_urgent', '-last_bumped_at', '-created_at'], 'verbose_name': 'Elan', 'verbose_name_plural': 'Elanlar'},
        ),
        migrations.AddField(
            model_name='listing',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_bumped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='urgent_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vip_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
