# Generated by Django 6.0.7 on 2026-07-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_options_listing_is_urgent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-is_vip', '-is_urgent', '-last_bumped_at', '-created_at'], 'verbose_name': 'Elan', 'verbose_name_plural': 'Elanlar'},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='featured_until',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_featured',
        ),
    ]
