# Generated by Django 6.0.7 on 2026-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_options_remove_listing_featured_until_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-is_vip', '-is_urgent', models.OrderBy(models.F('last_bumped_at'), descending=True, nulls_last=True), '-created_at'], 'verbose_name': 'Elan', 'verbose_name_plural': 'Elanlar'},
        ),
    ]
