# Generated by Django 6.0.7 on 2026-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
