# Generated by Django 6.0.7 on 2026-07-27 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('token_amount', models.PositiveIntegerField()),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promokod',
                'verbose_name_plural': 'Promokodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('bump', 'İrəli çək'), ('vip_7', 'VIP — 7 gün'), ('vip_10', 'VIP — 10 gün'), ('vip_30', 'VIP — 30 gün'), ('urgent_7', 'Təcili — 7 gün')], max_length=20, unique=True)),
                ('token_cost', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Xidmət Qiyməti',
                'verbose_name_plural': 'Xidmət Qiymətləri',
                'ordering': ['service_type'],
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Müsbət = artım, mənfi = xərclənmə')),
                ('transaction_type', models.CharField(choices=[('bonus', 'Qeydiyyat bonusu'), ('spend', 'Xərclənib'), ('purchase', 'Alış'), ('admin_add', 'Admin tərəfindən əlavə'), ('redeem', 'Promokod')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Tranzaksiyası',
                'verbose_name_plural': 'Token Tranzaksiyaları',
                'ordering': ['-created_at'],
            },
        ),
    ]
